config/routes.rb
Rails.application.routes.draw do
  root 'rides#index'  

  resources :rides, only: [:index, :new, :create, :show]
  resources :sessions, only: [:create]

  resources :users, only: [:create, :show] do
    resources :rides, only: [:new, :create]
  end

  get 'registration', to: 'users#new', as: 'registration'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'filter_by_state', to: 'rides#filter_by_state', as: 'filter_by_state'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :starting_city, presence: true
  validates :starting_state, presence: true
  validates :ending_city, presence: true
  validates :ending_state, presence: true
  validates :starting_address, presence: true
  validates :ending_address, presence: true
  validates :distance_in_miles, presence: true
  validates :star_rating, presence: true
  validates_inclusion_of :star_rating, in: 1..5, message: "must be between 1 and 5"

  def format_starting_address
    self.starting_address.split.join("+")
  end

  def format_ending_address
    self.ending_address.split.join("+")
  end

  def format_starting_city_and_state
    city_and_state = "#{self.starting_city} #{self.starting_state}"
    city_and_state.split.join("+")
  end

  def format_ending_city_and_state
    city_and_state = "#{self.ending_city} #{self.ending_state}"
    city_and_state.split.join("+")
  end  

  def format_starting_location
    "#{format_starting_address},#{format_starting_city_and_state}"
  end

  def format_ending_location
    "#{format_ending_address},#{format_ending_city_and_state}"
  end

  def self.filter_states
    states = Ride.all.pluck('starting_state') + Ride.all.pluck('ending_state')
    states.uniq.sort
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rides, foreign_key: :author_id

  validates :username, presence: true, uniqueness: true  
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  include SessionHelper

  def index
    respond_to(:html, :js)
    @rides = Ride.order(created_at: :desc)
    @state_list = Ride.filter_states
  end

  def new
    respond_to(:html, :js)
    @ride = Ride.new
    @state_list = state_list
  end

  def create
    respond_to(:html, :js)
    # For new ride being added
    @ride = Ride.new(ride_params)
    # For all rides when resetting state filter on create
    @rides = Ride.order(created_at: :desc)
    @state_list = state_list

    if @ride.save
      render :create
    else
      @errors = @ride.errors.full_messages
      render :new
    end
  end

  def show
    respond_to(:html, :js)
    @ride = Ride.find_by(id: params[:id])
    render :show
  end

  def filter_by_state
    @rides = Ride.all.select { |ride| ride.starting_state == params["state"] || ride.ending_state == params["state"] }
    @state_list = Ride.filter_states
  end  

  private
    def ride_params
      params.require(:ride).permit(:starting_city, :starting_state, :ending_city, :ending_state, :starting_address, :ending_address, :distance_in_miles, :star_rating, :author_id, :title)
    end

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionHelper

  def new
    respond_to(:html, :js)
    @user = User.new
  end

  def create
    respond_to(:html, :js)
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      render :create
    else
      @errors = ["Login failed."]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    respond_to(:html, :js)
    @user = User.new
  end

  def create
    respond_to(:html, :js)
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      render :create
    else
      @errors = @user.errors.full_messages
      render :new
    end
    
  end

  def show
    respond_to(:html, :js)
    @user = User.find_by(id: session[:user_id])
    @user_rides = @user.rides
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end

  def state_list
    @state_list = ['IL', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ride Reviews</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Racing+Sans+One",  media: 'all' %>
    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Chewy",  media: 'all' %>

    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Merriweather|Racing+Sans+One", media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'moto_favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="_qw76DYQkqeNyCmgLr5RwPKG86uwOvhCY6IxLokiygA" />
  </head>

  <body>
  <div class="site-container">
    <div class="navigation">
      <div class="navigation__login navigation__add-ride">
        <% if !current_user %>
          <%= link_to "User/Guest Login", login_path, remote: true, class: "navigation__login-link" %>
        <% else %>
          <%= link_to "Add Ride", new_ride_path, remote: true, class: "navigation__new-ride-link" %>
        <% end %>
      </div>
      <div class="navigation__center-box">
        <%= image_tag('https://source.unsplash.com/900x600/?motorcycle,winding-road', class: "box--slideshow_image_1") %>
        <%= image_tag('https://source.unsplash.com/901x600/?motorcycle,winding-road', class: "box--slideshow_image_2") %>
        <%= image_tag('https://source.unsplash.com/900x601/?motorcycle,winding-road', class: "box--slideshow_image_3") %>
        <%= image_tag('https://source.unsplash.com/902x600/?motorcycle,winding-road', class: "box--slideshow_image_4") %>
        <%= image_tag('https://source.unsplash.com/900x602/?motorcycle,winding-road', class: "box--slideshow_image_5") %>
      </div>
      <div class="navigation__registration navigation__user-rides">
        <% if !current_user %>
          <%= link_to "Register", registration_path, remote: true, class: "navigation__registration-link" %>
        <% else %>
          <%= link_to "Logout", logout_path, class: "navigation__logout-link" %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/rides/_all_rides.html.erb
<%= render 'rides/filter_by_state_form' %>
<% @rides.each do |ride|  %>
  <ul class="single-ride__list">
    <li class="rides-container__list-item rides-container__list-item--title">
    <%= link_to ride.title, ride, remote: true %>  
    </li>
    <li class="rides-container__list-item">Starting Location: <%= ride.starting_address %>, <%= ride.starting_city %>, <%= ride.starting_state %></li>
    <li class="rides-container__list-item">Ending Location: <%= ride.ending_address %>, <%= ride.ending_city %>, <%= ride.ending_state %></li>
    <li class="rides-container__list-item">Miles: <%= ride.distance_in_miles %></li>
    <li class="rides-container__list-item">Rating: <%= ride.star_rating %> stars</li>
  </ul>
<% end %>

app/views/rides/_created_ride.html.erb
<ul class="single-ride__list">
  <li class="rides-container__list-item rides-container__list-item--title"><%= link_to @ride.title, @ride, remote: true %></li>
  <li class="rides-container__list-item">Starting Location: <%= @ride.starting_address %>, <%= @ride.starting_city %>, <%= @ride.starting_state %></li>
  <li class="rides-container__list-item">Ending Location: <%= @ride.ending_address %>, <%= @ride.ending_city %>, <%= @ride.ending_state %></li>
  <li class="rides-container__list-item">Miles: <%= @ride.distance_in_miles %></li>
  <li class="rides-container__list-item">Rating: <%= @ride.star_rating %> stars</li>
</ul>

app/views/rides/_errors.html.erb
<% if @errors %>
  <% @errors.each do |msg| %>
    <p class="errors"><%= msg %></p>
  <% end %>
<% end %>

app/views/rides/_gmaps_embed.html.erb
<div class="map">
  <iframe
    width="600"
    height="450"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDjR6XtQpiT8AlkVBDoO6XQ03nuJNtLQgM
      &origin=<%= ride.format_starting_location %>
      &destination=<%= ride.format_ending_location %>" 
      allowfullscreen>
  </iframe>
</div>

app/views/rides/_new-ride-link.html.erb
<%= link_to "Add Ride", new_ride_path, remote: true, class: "navigation__center-box-new-ride-link" %>

app/views/rides/_new_ride_form.html.erb
<%= form_with model: @ride, class: "new-ride-form" do |f| %>
  <h3>Add a new ride!</h3>
  <%= f.text_field :title, placeholder: "Title", class: "new-ride-form__title" %><br>
  <%= f.text_field :starting_address, placeholder: "Starting Address" %>
  <%= f.text_field :starting_city, placeholder: "City", class: "new-ride-form__city" %>
  <%= f.select :starting_state, @state_list, class: "new-ride-form__state" %><br>
  <%= f.text_field :ending_address, placeholder: "Ending Address" %>
  <%= f.text_field :ending_city, placeholder: "City", class: "new-ride-form__city" %>
  <%= f.select :ending_state, @state_list, class: "new-ride-form__state" %><br>
  <%= f.text_field :distance_in_miles, placeholder: "Distance (in miles)" %><br>
  <label id="star-rate">Rate it!</label>
  <label id="star-one" class="rating-stars">&#9733;<%= f.radio_button :star_rating, "1" %></label>
  <label id="star-two" class="rating-stars">&#9733;<%= f.radio_button :star_rating, "2" %></label>
  <label id="star-three" class="rating-stars">&#9733;<%= f.radio_button :star_rating, "3" %></label>
  <label id="star-four" class="rating-stars">&#9733;<%= f.radio_button :star_rating, "4" %></label>
  <label id="star-five" class="rating-stars">&#9733;<%= f.radio_button :star_rating, "5" %></label>
  <br>

  <%= f.hidden_field :author_id, :value => current_user.id %>
  <%= f.submit "Create!", class: "new-ride-form__submit" %>
<% end %>

<%= render 'errors' if @errors %>

app/views/rides/_new_ride_link.html.erb
<%= link_to "Add Ride", new_ride_path, remote: true, class: "navigation__new-ride-link" %>

app/views/rides/_show_ride.html.erb
<ul class="single-ride__list">
  <%= link_to "Back to all rides", rides_path, remote: true %>
    <h2>Ride: <%= @ride.title %></h2>
      <li>Starts in <%= @ride.starting_city %>, <%= @ride.starting_state %> at <%= @ride.starting_address %></li>

      <li>Ends in <%= @ride.ending_city %>, <%= @ride.ending_state %> at <%= @ride.ending_address %></li>

      <li>
          <button class="rides-container__map-toggle">Toggle map</button>
        </li>
        <li class="map-item">
          <div class="map">
            
            <iframe
              width="600"
              height="450"
              frameborder="0" style="border:0"
              src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDjR6XtQpiT8AlkVBDoO6XQ03nuJNtLQgM
                &origin=<%= @ride.format_starting_location %>
                &destination=<%= @ride.format_ending_location %>" 
                allowfullscreen>
            </iframe>

          </div>
        </li>
      </ul>

app/views/rides/create.js.erb
$('.navigation__add-ride').find('.new-ride-form').remove()
$('.navigation__add-ride').find('.errors').remove() 
$('.navigation__add-ride').append('<%= j render ("new_ride_link") %>')

$(".rides-list").children().remove()
$(".rides-list").append('<%= j render ("all_rides") %>')
$('<%= j render ("created_ride") %>').insertAfter(".state-filter-form")

app/views/rides/filter_by_state.js.erb
$(".rides-list").children().remove()
$(".rides-list").append('<%= j render ("filter_by_state") %>')

app/views/rides/index.html.erb
<div class="rides-container">
  <h1 class="site-header"><%= link_to image_tag('ride_reviews_logo.png', size: "390x100"), rides_path %></h1>
  <div class="rides-list">
    <%= render 'rides/all_rides' %>
  </div>
</div>

app/views/rides/index.js.erb
$(".rides-list").children().remove()
$(".rides-list").append('<%= j render ("all_rides") %>')

app/views/rides/new.js.erb
$('.new-ride-form').trigger('reset')
$('.new-ride-form__title').focus()
$('.navigation__new-ride-link').remove()
$('.navigation__add-ride').find('.errors').remove()

if ($('.new-ride-form').length === 0) {
  $('.navigation__add-ride').append('<%= j render ("new_ride_form") %>')
}

$('.navigation__add-ride').append('<%= j render("errors") %>')

app/views/rides/show.html.erb
<div class="rides-container">
  <h1 class="site-header"><%= link_to image_tag('ride_reviews_logo.png', size: "390x100"), rides_path %></h1>
  
  <div class="rides-list">
    <ul class="single-ride__list">
    <h2>Ride: <%= @ride.title %></h2>
      <li>Starts in <%= @ride.starting_city %>, <%= @ride.starting_state %> at <%= @ride.starting_address %></li>

      <li>Ends in <%= @ride.ending_city %>, <%= @ride.ending_state %> at <%= @ride.ending_address %></li>

      <li>
          <button class="rides-container__map-toggle">Toggle map</button>
        </li>
        <li class="map-item">
          <div class="map">
            
            <iframe
              width="600"
              height="450"
              frameborder="0" style="border:0"
              src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDjR6XtQpiT8AlkVBDoO6XQ03nuJNtLQgM
                &origin=<%= @ride.format_starting_location %>
                &destination=<%= @ride.format_ending_location %>" 
                allowfullscreen>
            </iframe>

          </div>
        </li>
      </ul>
  </div>

</div>

app/views/users/_greeting.html.erb
<% if current_user %>
  <p>Hi, <%= current_user.username %>!</p>
<% end  %>

app/views/users/_logout.html.erb
<% if current_user %>
  <%= link_to "Logout", logout_path %>
<% end %>

app/views/users/_my_rides_link.html.erb
<p><%= current_user.username %>'s Rides</p>

app/views/users/_registration.html.erb
<%= form_with model: @user, class: "registration-form" do |f| %>
  <h2>Register</h2>
  <br>
  <%= f.text_field :username, placeholder: "Username", class: "registration-form__username" %><br>
  <%= f.text_field :email, placeholder: "Email" %><br>
  <%= f.password_field :password, placeholder: "Password" %><br>
  <%= f.submit "Register", class: "registration-form__submit" %>
<% end %>

<%= render 'errors' if @errors %>

app/views/users/_registration_link.html.erb
<%= link_to "Register", registration_path, remote: true, class: "navigation__registration-link" %>

app/views/users/create.js.erb
$('.registration-form').remove()
$('.errors').remove()
$('.navigation__login').find('.navigation__login-link').remove()
$('.login-form').remove()
$('.navigation__registration').append('<%= j render("sessions/logout") %>')
$('.navigation__add-ride').append('<%= j render ("rides/new_ride_link") %>')

app/views/users/new.js.erb
$('.registration-form').trigger('reset')
$('.registration-form__username').focus()
$('.navigation__registration-link').remove()
$('.navigation').find('.errors').remove()
$('.login-form').remove()

if ($('.navigation__login').find('.navigation__login-link').length === 0) {
  $('.navigation__login').append('<%= j render ("sessions/login_link") %>')
}

if ($('.registration-form').length === 0) {
  $('.navigation__registration').append('<%= j render("registration") %>')  
  $('.registration-form input').attr('autocomplete','off');
}

$('.navigation__registration').append('<%= j render("errors") %>')